### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by yanyiwu** [AschPlatform/asch-frontend#4]
```
➜  asch-frontend git:(master) npm i

> asch-frontend@1.2.0 preinstall /home/yanyiwu/code/asch-frontend
> bower install

module.js:487
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:40:20
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

**Comment by yanyiwu** [comment]
```
➜  asch-frontend git:(master) node -v
v8.1.4
➜  asch-frontend git:(master) node-gyp -v
v3.6.2
➜  asch-frontend git:(master) npm -v
1.3.10
```

**Comment by yanyiwu** [comment]
```
➜  asch-frontend git:(master) ✗ npm i

> asch-frontend@1.2.0 preinstall /home/yanyiwu/code/asch-frontend
> bower install

bower                     invalid-meta for:/home/yanyiwu/code/asch-frontend/bower.json
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> asch-frontend@1.2.0 postinstall /home/yanyiwu/code/asch-frontend
> npm run build


> asch-frontend@1.2.0 build /home/yanyiwu/code/asch-frontend
> browserify build.js -o bower_components/bitcore-mnemonic.js && cp node_modules/asch-js/browserify-asch.js bower_components/

Error: Cannot find module 'bitcore-mnemonic' from '/home/yanyiwu/code/asch-frontend'
```

**Comment by yanyiwu** [comment]
```
rm package-lock.json
```

and then `npm i` can fix this issue.
